services:
  - type: web
    name: mini-stackoverflow-backend
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 3
      - key: ALLOWED_HOSTS
        value: mini-stackoverflow-backend.onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: https://mini-stack-frontend.vercel.app,http://localhost:3000,http://127.0.0.1:3000
    healthCheckPath: /
    autoDeploy: true
    plan: free

databases:
  - name: postgres-db
    databaseName: mini_stackoverflow
    user: mini_stackoverflow_user
    plan: free

    