services:
  - type: web
    name: mini-stackoverflow-backend
    runtime: python
    buildCommand: "./build.sh"  # ‚Üê Utilisez ceci
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: postgres-db
    databaseName: mini_stackoverflow
    user: postgres
    plan: free
    